# Generated by Django 5.0.6 on 2026-04-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_importjob_id_alter_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
